# KioskDE default configuration

mode=web
target=https://tacobell.com

# security defaults
require_pin=true

# UI behavior
show_cursor=false
allow_alt_tab=false
allow_virtual_terminal=false

# system behavior
auto_launch=true
restart_on_exit=true
